networks:
  rustdesk-net:
    external: false

services:
  rustdesk-server:
    image: ${RUSTDESK_IMAGE:-ghcr.io/quanla93/rustdesk-server-s6:latest}
    container_name: ${CONTAINER_NAME:-rustdesk-server}
    restart: unless-stopped

    ports:
      - "${RUSTDESK_API_PORT:-21114}:21114"
      - "${RUSTDESK_NAT_PORT:-21115}:21115"
      - "${RUSTDESK_ID_PORT:-21116}:21116"
      - "${RUSTDESK_ID_PORT:-21116}:21116/udp"
      - "${RUSTDESK_RELAY_PORT:-21117}:21117"
      - "${RUSTDESK_WS_ID_PORT:-21118}:21118"
      - "${RUSTDESK_WS_RELAY_PORT:-21119}:21119"

    environment:
      RELAY: ${RUSTDESK_RELAY:-192.168.101.113}
      ENCRYPTED_ONLY: ${ENCRYPTED_ONLY:-1}
      MUST_LOGIN: ${MUST_LOGIN:-N}
      TZ: ${TZ:-Asia/Ho_Chi_Minh}

      RUSTDESK_API_RUSTDESK_ID_SERVER: ${RUSTDESK_ID_SERVER:-192.168.101.113:21116}
      RUSTDESK_API_RUSTDESK_RELAY_SERVER: ${RUSTDESK_RELAY_SERVER:-192.168.101.113:21117}
      RUSTDESK_API_RUSTDESK_API_SERVER: ${RUSTDESK_API_SERVER:-http://192.168.101.113:21114}
      RUSTDESK_API_RUSTDESK_KEY: ${RUSTDESK_KEY:-}
      RUSTDESK_API_JWT_KEY: ${RUSTDESK_API_JWT_KEY:-}

    volumes:
      - ${RUSTDESK_DATA_DIR:-/opt/rustdesk-server}/data/server:/data
      - ${RUSTDESK_DATA_DIR:-/opt/rustdesk-server}/data/api:/app/data
      - ${RUSTDESK_DATA_DIR:-/opt/rustdesk-server}/data/server:/app/conf/data

    networks:
      - rustdesk-net
