networks:
  rustdesk-net:
    external: false

services:
  rustdesk:
    ports:
      - 21114:21114
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      - 21118:21118
      - 21119:21119
    # Build directly from source to ensure static compilation on LXC
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      # TODO: Replace '100.64.39.126' with your LXC container's IP address or Domain Name
      - RELAY=100.64.39.126
      - ENCRYPTED_ONLY=1
      - MUST_LOGIN=N
      - TZ=Asia/Shanghai
      - RUSTDESK_API_RUSTDESK_ID_SERVER=100.64.39.126:21116
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=100.64.39.126:21117
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://100.64.39.126:21114
      - RUSTDESK_API_RUSTDESK_KEY=d16NpSSrNVneqJ2DqM1maPVGhYXeNokfm3ybJlicfro=
    volumes:
      - ./data/server:/data
      - ./data/api:/app/data
      - ./data/server:/app/conf/data
    networks:
      - rustdesk-net
    restart: unless-stopped
